spring:
    application:
        name: springtest
    datasource:
        url: jdbc:mysql://localhost:3306/mybatis
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

mqtttest:
    url: tcp://127.0.0.1:1883
    clientId: mqtt-test
    username: admin
    password: password